# Generated by Django 2.2.24 on 2022-02-28 07:03

from django.db import migrations


def fill_owner_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            owner=flat.owner,
        )
        owner.owned_flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220228_0805'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flats)
    ]
