# Generated by Django 2.2.24 on 2022-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220302_1210'),
    ]

    operations = [
    ]
